### ISSUE TITLE
Publish to caddyserver.com

### ISSUE THREAD

**Issue by hannseman** [mholt/caddy-events-exec#2]
Really looking forward to using this plugin, I would love to have it available on [caddyserver.com/download](https://caddyserver.com/download). Thanks!

**Comment by mholt** [comment]
Done :+1: Let me know your feedback as you use it!

**Comment by atticus-sullivan** [comment]
I recently stumbled over this feature of caddy / the plugin. Like it was discussed on multiple occasions (e.g. in the forum), my use-case would be to let caddy care about getting the certificate and then sync the cert+key so another service can use them (it uses "raw" tls and no http, so using caddy as proxy doesn't work).

So the command essentially would be something like
```bash
sudo cp .key .cert /other/dir/ && sudo chown my_service:my_service /other/dir/.key /other/dir/.crt && sudo chmod 0400 /other/dir/.key /other/dir/.crt
```
of course adjusting the `sudoers` to allow caddy to run the respective commands (and probably checking what additional flags can be used for hardening, like e.g. not following symlinks to avoid some attacks).

But tbh not being able to install caddy via the debian repository on cloudsmith anymore (as I'd need caddy with a specific plugin added to it) is a dealbreaker/huge hurdle for me.

Please don't get me wrong I don't want to stress anybody. I just wanted to share a "users" story. This won't stop me using caddy, but I'll need to keep on searching how I can solve the issue of securing and building that additional service.
(and sorry for waking up this very old issue, I just felt this would be the maybe right place to gather users interest, though if it is I see chances are low of this getting into "normal" caddy)

**Comment by mholt** [comment]
Thanks for your feedback.

> But tbh not being able to install caddy via the debian repository on cloudsmith anymore (as I'd need caddy with a specific plugin added to it) is a dealbreaker/huge hurdle for me.

You can still use it, with a diversion: https://caddyserver.com/docs/build#package-support-files-for-custom-builds-for-debianubunturaspbian

But yeah, it's annoying that these package managers don't make it possible to build a static binary with custom options, I guess. (Would love to be wrong about that.)

**Comment by atticus-sullivan** [comment]
Oh yes a second part of using the package is the ease of noticing an udate is available (and also installing it). This is probably one of the caveats using "static plugins".

One idea (at least for my usecase) I had is working around a bit by using a systemd-path unit. Not sure if I go that way, just wanted to leave it here as inspiration for someone digging this issue out in the future.
