### ISSUE TITLE
"context canceled" when trying to run echo via cmd.exe on windows

### ISSUE THREAD

**Issue by kmpm** [mholt/caddy-events-exec#3]
I know this is early days but I tried it out on windows using caddyfile, and as far as I can tell that forces me to run in background mode.

```
{
    events {
        on cached_managed_cert exec cmd.exe /c echo
    }
    debug
}



my.domain.dev {
	handle {
		respond "Site not served from here"
	}
}
```

When I run this i get 
```
2022/10/12 12:49:36.115 DEBUG   events  event   {"name": "cached_managed_cert", "id": "4e95e5ce-51f9-4c36-83cd-344476eb0cbe", "origin": "tls", "data": {"sans":["my.domain.dev"]}}
2022/10/12 12:49:36.122 INFO    tls     finished cleaning storage units
2022/10/12 12:49:36.130 ERROR   events.handlers.exec    background command failed       {"error": "context canceled"}
```
How do I avoid getting the context canceled using caddyfile syntax?

If I do a similar thing, but without running in a goroutine I get something usable.
```
// main.go
package main

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"time"
)

func main() {
	fmt.Println("exec called")
	ctx := context.Background()
	var cancel context.CancelFunc
	ctx, cancel = context.WithTimeout(ctx, 5*time.Second)
	cm := exec.CommandContext(ctx, "cmd.exe", "/C", "echo")
	defer cancel()

	cm.Stdout = os.Stdout
	cm.Stderr = os.Stderr

	if err := cm.Run(); err != nil {
		fmt.Printf("command failed: %v", err)
	}
}
```

```
go run ./
exec called
ECHO is on.
```

**Comment by kmpm** [comment]
I don't do a reload of config within that period. 
It happens on startup of caddy, directly after first cache of certs and I don't think caddy reloads the config itself unless changed and "--watch" but I am not that familiar of what happens then.

**Comment by kmpm** [comment]
Oh, and it works if I do a json config and set ` "foreground": true ` but I haven't found a way to set foreground using Caddyfile

**Comment by mholt** [comment]
Really, that is odd. I will try to reproduce this...

**Comment by mholt** [comment]
Oh, duh. I was able to reproduce it and will push a fix momentarily.

**Comment by mholt** [comment]
There we go. Please try that out!
