### ISSUE TITLE
Config Question

### ISSUE THREAD

**Issue by xombiemp** [mholt/caddy-events-exec#4]
I have this in my global config
  events {
    on cert_obtained exec /usr/local/bin/myscript
  }

Since this is in the global config, this will be triggered when ANY cert is obtained, right?  What if I only want it triggered when a cert for a specific domain is obtained?  I tried putting it in a specific site block, but I got an error saying unrecognized directive: events.

**Comment by mholt** [comment]
Yeah, so far that is a limitation of this. It's good to know there is a request for this feature though.

The domain name is contained in the event data, so it should be a matter of exposing config that lets the user customize event subscriptions to handle conditional upon event data. I'm not actually sure that's the right way to do that yet, but it's one option.

I think a better option would be to simply pass the relevant event data into your program and let your program's logic decide what to do. The domain name can be accessed through the `{event.data.identifier}` placeholder, for example: `on cert_obtained exec /usr/local/bin/myscript --domain {event.data.identifier}`

**Comment by xombiemp** [comment]
Thanks, I'll give that a try. I have been rate limited because I've reissued too many certs in my testing, so I'll need to wait a bit.

**Comment by mholt** [comment]
(Oof, always use Let's Encrypt's staging endpoint if you are testing!)

**Comment by xombiemp** [comment]
Ok, that worked! Thanks for the explanation and example!
