### ISSUE TITLE
How to exec echo command?

### ISSUE THREAD

**Issue by loeffelpan** [mholt/caddy-events-exec#7]
I'm trying to execute something outside of caddy running in a docker container.
The original purpose is to copy certificate to another directory on `cert_obtained`. But the directory isn't accessable for caddy inside the container. I did something similar with another container and a named pipe.
The idea is to echo some to a named pipe in a directory shared with the host. On the host there is script monitoring the named pipe and executing the real command.

I added this to my `Caddyfile` for testing, where `/data/host.pipe` is a regular file.
```
events {
	on tls_get_certificate exec /bin/sh -c 'echo caddy_cert {event.data.client_hello} >> /data/host.pipe'
}
```

Caddy gives me this error. Can you please help to get that echo command in the correct format?
`{"level":"error","ts":"2024/05/02 14:27:25","logger":"events.handlers.exec","msg":"background command failed","error":"exit status 2"}`

Using `exec echo foo > bar` just echoes exactly that to containers console and ignores redirection.

**Comment by mholt** [comment]
What else is in the logs? Caddy sets the stdout and stderr to that of the Caddy process so you can capture/observe it as well.

**Comment by loeffelpan** [comment]
Correct. I missed that in the logs.
```
caddy_cert: line 0: syntax error: unterminated quoted string
{"level":"error","ts":"2024/05/02 17:02:53","logger":"events.handlers.exec","msg":"background command failed","error":"exit status 2"}
```

**Comment by mholt** [comment]
Oh, the Caddyfile quotes are `"` (or <code>`</code>) only. First the Caddyfile has to parse your tokens, then it feeds those into a command as arguments. (There is no shell, despite the appearance of a shell command.)

So replace `'` with `"` and see if that works.

**Comment by loeffelpan** [comment]
Thanks. Your advice with different quotes was correct.
I endet up with this and it's working:

```
	events {
		on cert_obtained exec /bin/sh -c "echo caddy_cert {event.data.certificate_path} {event.data.private_key_path} > /data/host.pipe"
	}
```
